from __future__ import annotations

AID_DEFAULT_URL_SCHEME = "https"
AID_CATALOG_MODE = "catalog"
AID_ROBOTS_MODE = "robots"
AID_SITEMAP_MODE = "sitemap"

AID_AUDIT_JOB_STATUS_QUEUED = "queued"
AID_AUDIT_JOB_STATUS_RUNNING = "running"
AID_AUDIT_JOB_STATUS_COMPLETE = "complete"
AID_AUDIT_JOB_STATUS_FAILED = "failed"
AID_AUDIT_DEFAULT_SAMPLE_SIZE = 5
AID_AUDIT_MAX_SAMPLE_SIZE = 50
AID_AUDIT_DEFAULT_REPORT_FORMATS = ("json", "markdown")
AID_CRAWL_TIMEOUT_SECONDS = 10.0
AID_ROBOTS_TIMEOUT_SECONDS = 5.0
AID_SITEMAP_TIMEOUT_SECONDS = 5.0
AID_LLM_TASK = "aid_discoverability_audit"
AID_LLM_TIMEOUT_SECONDS = 30.0
AID_LLM_MAX_PAGES = 5
AID_PRICE_CONTRADICTION_THRESHOLD = 0.05
AID_DESCRIPTION_MIN_CHARS = 100
AID_VISIBLE_DESCRIPTION_MIN_CHARS = 500
AID_PAGE_EVIDENCE_EXCERPT_CHARS = 6000
AID_VISIBLE_DESCRIPTION_SIGNAL_TERMS = (
    "benefit",
    "benefits",
    "features",
    "ingredient",
    "ingredients",
    "how to use",
    "usage",
    "suitable",
    "material",
    "specification",
    "specifications",
    "care",
)
AID_LLM_FAIL_PENALTY = 18
AID_LLM_PARTIAL_PENALTY = 6

AID_STATUS_PASS = "pass"
AID_STATUS_WARNING = "warning"
AID_STATUS_FAIL = "fail"
AID_FINDING_BLOCKING = "blocking"
AID_FINDING_WARNING = "warning"
AID_FINDING_INFO = "info"

D_AID1_ID = "D-AID1"
D_AID2_ID = "D-AID2"
D_AID3_ID = "D-AID3"
D_AID4_ID = "D-AID4"
D_AID5_ID = "D-AID5"
D_AID6_ID = "D-AID6"
DIMENSION_WEIGHTS = {
    D_AID1_ID: 0.20,
    D_AID2_ID: 0.25,
    D_AID3_ID: 0.20,
    D_AID4_ID: 0.15,
    D_AID5_ID: 0.10,
    D_AID6_ID: 0.10,
}
D_AID1_GATE_MAX_SCORE = 30
D_AID3_GATE_MAX_SCORE = 0

FINDING_AID1_JSONLD_MISSING = "AID1_JSONLD_MISSING"
FINDING_AID1_PRODUCT_TYPE_MISSING = "AID1_PRODUCT_TYPE_MISSING"
FINDING_AID1_OPEN_GRAPH_MISSING = "AID1_OPEN_GRAPH_MISSING"
FINDING_AID1_SCHEMA_INVALID = "AID1_SCHEMA_INVALID"

FINDING_AID2_TITLE_MISSING = "AID2_TITLE_MISSING"
FINDING_AID2_PRICE_MISSING = "AID2_PRICE_MISSING"
FINDING_AID2_DESCRIPTION_SHORT = "AID2_DESCRIPTION_SHORT"
FINDING_AID2_IMAGES_MISSING = "AID2_IMAGES_MISSING"
FINDING_AID2_VARIANTS_MISSING = "AID2_VARIANTS_MISSING"
FINDING_AID2_IDENTIFIERS_MISSING = "AID2_IDENTIFIERS_MISSING"

FINDING_AID3_OFFER_MISSING = "AID3_OFFER_MISSING"
FINDING_AID3_PAYMENT_METHODS_MISSING = "AID3_PAYMENT_METHODS_MISSING"
FINDING_AID3_EMI_SIGNAL_MISSING = "AID3_EMI_SIGNAL_MISSING"
FINDING_AID3_DELIVERY_ETA_MISSING = "AID3_DELIVERY_ETA_MISSING"
FINDING_AID3_RETURN_POLICY_MISSING = "AID3_RETURN_POLICY_MISSING"

FINDING_AID4_AVAILABILITY_MISSING = "AID4_AVAILABILITY_MISSING"
FINDING_AID4_PRICE_STALE = "AID4_PRICE_STALE"
FINDING_AID4_OUT_OF_STOCK_RATE_HIGH = "AID4_OUT_OF_STOCK_RATE_HIGH"

FINDING_AID5_RATING_MISSING = "AID5_RATING_MISSING"
FINDING_AID5_REVIEW_COUNT_ZERO = "AID5_REVIEW_COUNT_ZERO"
FINDING_AID5_REVIEW_SCHEMA_INVALID = "AID5_REVIEW_SCHEMA_INVALID"

FINDING_AID6_LOCAL_BUSINESS_MISSING = "AID6_LOCAL_BUSINESS_MISSING"
FINDING_AID6_ROBOTS_BLOCKING_AI = "AID6_ROBOTS_BLOCKING_AI"
FINDING_AID6_SITEMAP_MISSING = "AID6_SITEMAP_MISSING"

FINDING_AID_LLM_IDENTITY_UNCLEAR = "AID_LLM_IDENTITY_UNCLEAR"
FINDING_AID_LLM_VARIANTS_MISSING = "AID_LLM_VARIANTS_MISSING"
FINDING_AID_LLM_VARIANTS_UNRESOLVABLE = "AID_LLM_VARIANTS_UNRESOLVABLE"
FINDING_AID_LLM_DESCRIPTION_FLUFF = "AID_LLM_DESCRIPTION_FLUFF"
FINDING_AID_LLM_DESCRIPTION_SHORT = "AID_LLM_DESCRIPTION_SHORT"
FINDING_AID_LLM_INTENT_UNANSWERABLE = "AID_LLM_INTENT_UNANSWERABLE"
FINDING_AID_LLM_COHERENCE_CONTRADICTION = "AID_LLM_COHERENCE_CONTRADICTION"
FINDING_AID_LLM_COHERENCE_INCOMPLETE = "AID_LLM_COHERENCE_INCOMPLETE"
FINDING_AID_LLM_RECOMMENDATION_LOW_CONFIDENCE = "AID_LLM_RECOMMENDATION_LOW_CONFIDENCE"
FINDING_AID_LLM_INSUFFICIENT_EVIDENCE = "AID_LLM_INSUFFICIENT_EVIDENCE"

AID_LLM_RUBRIC_DIMENSIONS = (
    "semantic_identity",
    "variant_inferability",
    "intent_answerability",
    "description_quality",
    "cross_signal_coherence",
    "recommendation_confidence",
)
AID_LLM_DIMENSION_TO_AID = {
    "semantic_identity": D_AID2_ID,
    "variant_inferability": D_AID2_ID,
    "intent_answerability": D_AID3_ID,
    "description_quality": D_AID2_ID,
    "cross_signal_coherence": D_AID4_ID,
    "recommendation_confidence": D_AID5_ID,
}
AID_LLM_BLOCKING_DIMENSIONS = ("semantic_identity", "intent_answerability")
AID_SCORE_PROMPT_REGISTRY = {
    AID_LLM_TASK: {
        "response_type": "object",
        "system_file": "aid_discoverability_audit.system.txt",
        "user_file": "aid_discoverability_audit.user.txt",
    },
}
