"""JS-state field mapping specs."""

from __future__ import annotations

from glom import Coalesce  # type: ignore[import-untyped]

JS_STATE_GLOM_SKIP: tuple[object, ...] = ("", [], {})
JS_STATE_PRODUCT_PAYLOAD_LIMIT = 24
JS_STATE_LIST_ITERATION_LIMIT = 25
JS_STATE_PRODUCT_VARIANT_LIST_KEYS: tuple[str, ...] = (
    "variants",
    "availableSizes",
    "variation_hierarchy",
)
JS_STATE_PRODUCT_OPTION_GROUP_KEYS: tuple[str, ...] = (
    "options",
    "configurable_product_options",
    "configurableProductOptions",
)
JS_STATE_OPTION_GROUP_VALUE_KEYS: tuple[str, ...] = (
    "values",
    "options",
)
JS_STATE_VARIANT_AVAILABILITY_BOOL_KEYS: tuple[str, ...] = (
    "available",
    "availableForSale",
    "inStock",
    "isInStock",
    "enabled",
    "in_stock",
)
JS_STATE_VARIANT_STOCK_QUANTITY_KEYS: tuple[str, ...] = (
    "inventory_quantity",
    "stock_quantity",
    "quantity",
    "inventoryQuantity",
    "stock",
)
VARIANT_AXIS_KEYS = (
    "color",
    "size",
    "style",
    "material",
    "flavor",
    "scent",
    "capacity",
    "length",
    "width",
    "condition",
    "grade",
    "storage",
    "memory",
    "finish",
    "model",
)
JS_STATE_PRODUCT_FIELD_SPEC = {
    "title": Coalesce(
        "title",
        "name",
        "nameByLanguage.en",
        "pn",
        "copyProductTitle",
        "item.product_description.title",
        default=None,
        skip=JS_STATE_GLOM_SKIP,
    ),
    "brand": Coalesce(
        "brand.name",
        "brand",
        "brandName",
        "vendor.name",
        "vendor",
        "labelDisplayName",
        "newBrand.name.en",
        default=None,
        skip=JS_STATE_GLOM_SKIP,
    ),
    "vendor": Coalesce("vendor.name", "vendor", default=None, skip=JS_STATE_GLOM_SKIP),
    "url": Coalesce(
        "url",
        "href",
        "onlineStoreUrl",
        "online_store_url",
        "productUrl",
        "product_url",
        "canonicalUrl",
        "canonical_url",
        "item.enrichment.buy_url",
        "websiteUrl",
        default=None,
        skip=JS_STATE_GLOM_SKIP,
    ),
    "handle": Coalesce("handle", "slug", default=None, skip=JS_STATE_GLOM_SKIP),
    "description": Coalesce(
        "description",
        "body_html",
        "descriptionHtml",
        "descriptionByLanguage.en",
        "copyDescription",
        "pd",
        default=None,
        skip=JS_STATE_GLOM_SKIP,
    ),
    "product_id": Coalesce(
        "id",
        "product_id",
        "productId",
        "tcin",
        "pid",
        "legacyResourceId",
        "legacyStyleGroupId",
        default=None,
        skip=JS_STATE_GLOM_SKIP,
    ),
    "category": Coalesce("category", default=None, skip=JS_STATE_GLOM_SKIP),
    "product_type": Coalesce(
        "product_type", "productType", "type", default=None, skip=JS_STATE_GLOM_SKIP
    ),
    "gender": Coalesce(
        "gender", "target_gender", "targetGender", default=None, skip=JS_STATE_GLOM_SKIP
    ),
    "sku": Coalesce(
        "sku.skuId", "sku", "productCode", default=None, skip=JS_STATE_GLOM_SKIP
    ),
    "barcode": Coalesce("barcode", default=None, skip=JS_STATE_GLOM_SKIP),
    "currency": Coalesce(
        "currency",
        "currencyCode",
        "priceCurrency",
        "prices.currency",
        "prices.currentPrice.currencyCode",
        "productPrice.currency",
        "pricing_information.currency",
        "pricing_information.currentPrice.currencyCode",
        "prices.promo.currency.code",
        "prices.base.currency.code",
        "prices.promo.currencyCode",
        "prices.base.currencyCode",
        "priceRange.minVariantPrice.currencyCode",
        "priceRange.maxVariantPrice.currencyCode",
        default=None,
        skip=JS_STATE_GLOM_SKIP,
    ),
    "price": Coalesce(
        "price",
        "amount",
        "minPrice",
        "maxPrice",
        "formattedPrice",
        "salePrice",
        "salePrice.amount",
        "salePrice.value",
        "currentPrice",
        "currentPrice.amount",
        "currentPrice.value",
        "productPrice.current.value",
        "productPrice.current.text",
        "prices.currentPrice",
        "prices.currentPrice.amount",
        "pricing_information.currentPrice",
        "pricing_information.currentPrice.amount",
        "pricing_information.standard_price",
        "prices.promo.value",
        "prices.base.value",
        "prices.promo.amount",
        "prices.base.amount",
        "priceRange.minVariantPrice.amount",
        "priceRange.maxVariantPrice.amount",
        default=None,
        skip=JS_STATE_GLOM_SKIP,
    ),
    "original_price": Coalesce(
        "compare_at_price",
        "compareAtPrice",
        "original_price",
        "originalPrice",
        "listPrice",
        "fullPrice",
        "fullPrice.amount",
        "prices.initialPrice",
        "prices.initialPrice.amount",
        "pricing_information.standard_price",
        "pricing_information.listPrice",
        "prices.base.value",
        "prices.base.amount",
        "compareAtPriceRange.minVariantPrice.amount",
        "compareAtPriceRange.maxVariantPrice.amount",
        "mrp",
        default=None,
        skip=JS_STATE_GLOM_SKIP,
    ),
    "availability": Coalesce(
        "availability",
        "inventory.status",
        "availableForSale",
        default=None,
        skip=JS_STATE_GLOM_SKIP,
    ),
    "tags": Coalesce("tags", default=None, skip=JS_STATE_GLOM_SKIP),
    "created_at": Coalesce("created_at", default=None, skip=JS_STATE_GLOM_SKIP),
    "updated_at": Coalesce("updated_at", default=None, skip=JS_STATE_GLOM_SKIP),
    "published_at": Coalesce("published_at", default=None, skip=JS_STATE_GLOM_SKIP),
}
JS_STATE_VARIANT_FIELD_SPEC = {
    "url": Coalesce(
        "url",
        "href",
        "onlineStoreUrl",
        "online_store_url",
        "productUrl",
        "product_url",
        "canonicalUrl",
        "canonical_url",
        "buy_url",
        default=None,
        skip=JS_STATE_GLOM_SKIP,
    ),
    "price": Coalesce(
        "price.amount",
        "price.value",
        "priceV2.amount",
        "priceV2.value",
        "salePrice.amount",
        "salePrice.value",
        "salePrice",
        "currentPrice.amount",
        "currentPrice.value",
        "currentPrice",
        "price.current.value",
        "price.current.text",
        "prices.currentPrice",
        "prices.currentPrice.amount",
        "sku.propositions.0.pricings.0.sellingRetail.price",
        "sellingRetail.price",
        "sellingRetailPriceRange.min",
        "amount",
        "formattedPrice",
        "price",
        default=None,
        skip=JS_STATE_GLOM_SKIP,
    ),
    "original_price": Coalesce(
        "compare_at_price.amount",
        "compare_at_price",
        "compareAtPrice.amount",
        "compareAtPriceV2.amount",
        "compareAtPrice",
        "original_price",
        "originalPrice",
        "listPrice.amount",
        "listPrice",
        "fullPrice.amount",
        "fullPrice",
        "prices.initialPrice",
        "prices.initialPrice.amount",
        "sku.propositions.0.pricings.0.baseRetail.price",
        "baseRetail.price",
        "baseRetailPriceRange.min",
        default=None,
        skip=JS_STATE_GLOM_SKIP,
    ),
    "currency": Coalesce(
        "currency",
        "currencyCode",
        "priceCurrency",
        "currentPrice.currencyCode",
        "salePrice.currencyCode",
        "prices.currency",
        "price.currency",
        "price.currencyCode",
        "price.currency_code",
        "priceV2.currencyCode",
        "compareAtPrice.currencyCode",
        "compareAtPriceV2.currencyCode",
        default=None,
        skip=JS_STATE_GLOM_SKIP,
    ),
    "sku": Coalesce("sku.skuId", "sku", default=None, skip=JS_STATE_GLOM_SKIP),
    "barcode": Coalesce("barcode", default=None, skip=JS_STATE_GLOM_SKIP),
}
