from __future__ import annotations

from app.services.config.surface_detection import (
    PUBLIC_SURFACE_ARTICLE,
    PUBLIC_SURFACE_AUTO,
    PUBLIC_SURFACE_CONTENT,
    PUBLIC_SURFACE_ECOMMERCE,
    PUBLIC_SURFACE_FORUM_THREAD,
    PUBLIC_SUPPORTED_SURFACES,
)

PUBLIC_API_KEY_PREFIX = "cai_"
PUBLIC_API_KEY_BYTES = 32
PUBLIC_API_KEY_PREFIX_DISPLAY_LENGTH = 12

PUBLIC_API_STATUS_OK = "ok"
PUBLIC_API_STATUS_ERROR = "error"

PUBLIC_API_SURFACE_AUTO = PUBLIC_SURFACE_AUTO
PUBLIC_API_SURFACE_ECOMMERCE = PUBLIC_SURFACE_ECOMMERCE
PUBLIC_API_SURFACE_CONTENT = PUBLIC_SURFACE_CONTENT
PUBLIC_API_SURFACE_ARTICLE = PUBLIC_SURFACE_ARTICLE
PUBLIC_API_SURFACE_FORUM_THREAD = PUBLIC_SURFACE_FORUM_THREAD
PUBLIC_API_INTERNAL_ECOMMERCE_SURFACE = "ecommerce_detail"
PUBLIC_API_SUPPORTED_SURFACES = PUBLIC_SUPPORTED_SURFACES

PUBLIC_API_DEFAULT_ECOMMERCE_FIELDS = (
    "title",
    "price",
    "currency",
    "availability",
    "sku",
    "image_url",
    "additional_images",
    "variants",
)
PUBLIC_API_DEFAULT_FIELDS_BY_SURFACE = {
    "ecommerce_detail": PUBLIC_API_DEFAULT_ECOMMERCE_FIELDS,
    "ecommerce_listing": ("title", "price", "image_url", "url"),
    "content_detail": ("title", "content", "url"),
    "content_listing": ("title", "url"),
    "article_detail": ("title", "author", "publication_date", "content", "url"),
    "article_listing": ("title", "publication_date", "author", "url"),
    "forum_detail": ("title", "author", "content", "reply_count", "view_count", "url"),
}
PUBLIC_API_FIELD_ALIASES = {
    "product_name": "title",
    "name": "title",
    "images": "additional_images",
    "image": "image_url",
}

PUBLIC_API_MAX_WAIT_SECONDS = 10
PUBLIC_API_DEFAULT_MAX_WAIT_SECONDS = PUBLIC_API_MAX_WAIT_SECONDS
PUBLIC_API_MAX_BATCH_URLS = 100

PUBLIC_API_RATE_LIMIT_WINDOW_SECONDS = 60
PUBLIC_API_BURST_WINDOW_SECONDS = 5
PUBLIC_API_EXTRACT_RATE_LIMIT = 60
PUBLIC_API_EXTRACT_BURST_LIMIT = 10
PUBLIC_API_READ_RATE_LIMIT = 600
PUBLIC_API_READ_BURST_LIMIT = 100
PUBLIC_API_RATE_LIMIT_MAX_BUCKETS = 10_000

PUBLIC_API_ERROR_API_KEY_REQUIRED = "API_KEY_REQUIRED"
PUBLIC_API_ERROR_AUTH_UNAVAILABLE = "AUTH_UNAVAILABLE"
PUBLIC_API_ERROR_INVALID_API_KEY = "INVALID_API_KEY"
PUBLIC_API_ERROR_RATE_LIMITED = "RATE_LIMITED"
PUBLIC_API_ERROR_INVALID_URL = "INVALID_URL"
PUBLIC_API_ERROR_INVALID_SURFACE = "INVALID_SURFACE"
PUBLIC_API_ERROR_INVALID_FIELD = "INVALID_FIELD"
PUBLIC_API_ERROR_TIMEOUT = "TIMEOUT"
PUBLIC_API_ERROR_EXTRACTION_FAILED = "EXTRACTION_FAILED"
PUBLIC_API_ERROR_BROWSER_REQUIRED = "BROWSER_REQUIRED"
PUBLIC_API_ERROR_WORKER_REQUIRED = "WORKER_REQUIRED"
PUBLIC_API_ERROR_NOT_IMPLEMENTED = "NOT_IMPLEMENTED"
PUBLIC_API_ERROR_URL_UNREACHABLE = "URL_UNREACHABLE"
PUBLIC_API_ERROR_BOT_BLOCK = "BOT_BLOCK"

PUBLIC_API_MCP_API_KEY_ENV = "CRAWLERAI_API_KEY"
PUBLIC_API_MCP_BASE_URL_ENV = "CRAWLERAI_API_BASE_URL"
PUBLIC_API_MCP_DEFAULT_BASE_URL = "https://api.crawlerai.com/api/v1"

PUBLIC_API_CAPABILITIES = {
    "version": "v1",
    "surfaces": sorted(PUBLIC_API_SUPPORTED_SURFACES),
    "tools": [
        "extract_product",
        "alert_product",
        "get_alert_status",
        "cancel_alert",
        "list_alerts",
        "check_domain",
        "list_capabilities",
    ],
    "deferred": ["extract_batch"],
    "deployment": "railway-ready",
}
