from __future__ import annotations

SITEMAP_DEFAULT_FILTER_KEYWORD = ""
SITEMAP_DEFAULT_MAX_URLS = 500
SITEMAP_FETCH_TIMEOUT_SECONDS = 15
SITEMAP_FETCH_RETRY_ATTEMPTS = 2
SITEMAP_FETCH_RETRY_DELAY_SECONDS = 0.5
SITEMAP_FETCH_RETRY_STATUS_CODES = (429, 502, 503, 504)
SITEMAP_USER_AGENT = "Mozilla/5.0 (compatible; CrawlwiseBot/1.0)"
