"""canonical invoro schema"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "20260822_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domain_cookie_memory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column(
            "storage_state", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("state_fingerprint", sa.String(length=128), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_domain_cookie_memory_domain",
        "domain_cookie_memory",
        ["domain"],
        unique=True,
    )
    op.create_table(
        "domain_memory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("surface", sa.String(length=40), nullable=False),
        sa.Column("platform", sa.String(length=40), nullable=True),
        sa.Column("selectors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_domain_memory_domain"), "domain_memory", ["domain"], unique=False
    )
    op.create_index(
        op.f("ix_domain_memory_surface"), "domain_memory", ["surface"], unique=False
    )
    op.create_table(
        "domain_run_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("surface", sa.String(length=40), nullable=False),
        sa.Column("profile", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_domain_run_profiles_domain_surface",
        "domain_run_profiles",
        ["domain", "surface"],
        unique=True,
    )
    op.create_table(
        "host_protection_memory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column("hard_block_count", sa.Integer(), nullable=False),
        sa.Column("browser_first_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("proxy_required_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_block_vendor", sa.String(length=64), nullable=True),
        sa.Column("last_block_status_code", sa.Integer(), nullable=True),
        sa.Column("last_block_method", sa.String(length=32), nullable=True),
        sa.Column("last_blocked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_method", sa.String(length=32), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_host_protection_memory_host",
        "host_protection_memory",
        ["host"],
        unique=True,
    )
    op.create_table(
        "llm_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("api_key_encrypted", sa.Text(), nullable=False),
        sa.Column("task_type", sa.String(length=60), nullable=False),
        sa.Column(
            "per_domain_daily_budget_usd",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
        ),
        sa.Column(
            "global_session_budget_usd",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("token_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("key_prefix", sa.String(length=16), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_api_keys_is_active"), "api_keys", ["is_active"], unique=False
    )
    op.create_index(op.f("ix_api_keys_key_hash"), "api_keys", ["key_hash"], unique=True)
    op.create_index(
        op.f("ix_api_keys_key_prefix"), "api_keys", ["key_prefix"], unique=False
    )
    op.create_index(op.f("ix_api_keys_user_id"), "api_keys", ["user_id"], unique=False)
    op.create_table(
        "crawl_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("run_type", sa.String(length=20), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("surface", sa.String(length=40), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "requested_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "result_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("queue_owner", sa.String(length=64), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claim_count", sa.Integer(), nullable=False),
        sa.Column("last_claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_crawl_runs_status"), "crawl_runs", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_crawl_runs_user_id"), "crawl_runs", ["user_id"], unique=False
    )
    op.create_table(
        "monitor_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("urls", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("domains", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("surface", sa.String(length=40), nullable=False),
        sa.Column(
            "tracked_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("schedule_interval_hours", sa.Integer(), nullable=False),
        sa.Column("priority", sa.String(length=32), nullable=False),
        sa.Column("retention_days", sa.Integer(), nullable=False),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "requested_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("condition", sa.Text(), nullable=True),
        sa.Column("webhook_url", sa.Text(), nullable=True),
        sa.Column("poll_interval_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "last_known_values", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_failure_count", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("last_crawl_method", sa.String(length=32), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_monitor_jobs_priority"), "monitor_jobs", ["priority"], unique=False
    )
    op.create_index(
        op.f("ix_monitor_jobs_status"), "monitor_jobs", ["status"], unique=False
    )
    op.create_index(
        "ix_monitor_jobs_status_priority_next_run",
        "monitor_jobs",
        ["status", "priority", "next_run_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monitor_jobs_user_id"), "monitor_jobs", ["user_id"], unique=False
    )
    op.create_table(
        "playground_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("input_url", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("step_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_playground_sessions_user_id"),
        "playground_sessions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "crawl_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("level", sa.String(length=20), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["crawl_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_crawl_logs_run_id"), "crawl_logs", ["run_id"], unique=False
    )
    op.create_table(
        "crawl_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("url_identity_key", sa.String(length=64), nullable=True),
        sa.Column("content_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "discovered_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "source_trace", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("raw_html_path", sa.Text(), nullable=True),
        sa.Column(
            "enrichment_status",
            sa.String(length=32),
            server_default="unenriched",
            nullable=False,
        ),
        sa.Column("enriched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["crawl_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_crawl_records_enrichment_status"),
        "crawl_records",
        ["enrichment_status"],
        unique=False,
    )
    op.create_index(
        "ix_crawl_records_run_content_fp",
        "crawl_records",
        ["run_id", "content_fingerprint"],
        unique=False,
    )
    op.create_index(
        op.f("ix_crawl_records_run_id"), "crawl_records", ["run_id"], unique=False
    )
    op.create_index(
        "uq_crawl_records_run_identity",
        "crawl_records",
        ["run_id", "url_identity_key"],
        unique=True,
        postgresql_where=sa.text("url_identity_key IS NOT NULL"),
    )
    op.create_table(
        "data_enrichment_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("source_run_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_run_id"], ["crawl_runs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_enrichment_jobs_source_run_id"),
        "data_enrichment_jobs",
        ["source_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_enrichment_jobs_status"),
        "data_enrichment_jobs",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_enrichment_jobs_user_id"),
        "data_enrichment_jobs",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "domain_field_feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("surface", sa.String(length=40), nullable=False),
        sa.Column("field_name", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column("source_value", sa.Text(), nullable=True),
        sa.Column("source_run_id", sa.Integer(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_run_id"], ["crawl_runs.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_domain_field_feedback_domain_surface",
        "domain_field_feedback",
        ["domain", "surface"],
        unique=False,
    )
    op.create_index(
        op.f("ix_domain_field_feedback_field_name"),
        "domain_field_feedback",
        ["field_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_domain_field_feedback_source_run_id"),
        "domain_field_feedback",
        ["source_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_domain_field_feedback_surface"),
        "domain_field_feedback",
        ["surface"],
        unique=False,
    )
    op.create_table(
        "in_app_notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("monitor_id", sa.Integer(), nullable=False),
        sa.Column("event_count", sa.Integer(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["monitor_id"], ["monitor_jobs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_in_app_notifications_monitor_id"),
        "in_app_notifications",
        ["monitor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_in_app_notifications_read"),
        "in_app_notifications",
        ["read"],
        unique=False,
    )
    op.create_index(
        op.f("ix_in_app_notifications_user_id"),
        "in_app_notifications",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_in_app_notifications_user_read_created",
        "in_app_notifications",
        ["user_id", "read", "created_at"],
        unique=False,
    )
    op.create_table(
        "llm_cost_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("task_type", sa.String(length=60), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("error_category", sa.String(length=60), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "outcome in ('success', 'error')", name="ck_llm_cost_log_outcome"
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["crawl_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_llm_cost_log_run_id"), "llm_cost_log", ["run_id"], unique=False
    )
    op.create_table(
        "monitor_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("monitor_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("field_name", sa.String(length=255), nullable=True),
        sa.Column("old_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notification_status", sa.String(length=32), nullable=False),
        sa.Column("condition_met", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["monitor_id"], ["monitor_jobs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["run_id"], ["crawl_runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_monitor_events_condition_met"),
        "monitor_events",
        ["condition_met"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monitor_events_detected_at"),
        "monitor_events",
        ["detected_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monitor_events_event_type"),
        "monitor_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monitor_events_field_name"),
        "monitor_events",
        ["field_name"],
        unique=False,
    )
    op.create_index(
        "ix_monitor_events_monitor_detected",
        "monitor_events",
        ["monitor_id", "detected_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monitor_events_monitor_id"),
        "monitor_events",
        ["monitor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monitor_events_notification_status"),
        "monitor_events",
        ["notification_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monitor_events_run_id"), "monitor_events", ["run_id"], unique=False
    )
    op.create_table(
        "monitor_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("monitor_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column(
            "snapshot_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("record_count", sa.Integer(), nullable=False),
        sa.Column("change_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["monitor_id"], ["monitor_jobs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["run_id"], ["crawl_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_monitor_snapshots_monitor_created",
        "monitor_snapshots",
        ["monitor_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monitor_snapshots_monitor_id"),
        "monitor_snapshots",
        ["monitor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monitor_snapshots_run_id"),
        "monitor_snapshots",
        ["run_id"],
        unique=False,
    )
    op.create_table(
        "monitor_url_states",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("monitor_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("last_etag", sa.Text(), nullable=True),
        sa.Column("last_modified", sa.Text(), nullable=True),
        sa.Column("last_content_hash", sa.String(length=64), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consecutive_unchanged_count", sa.Integer(), nullable=False),
        sa.Column("auto_downgraded", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["monitor_id"], ["monitor_jobs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_monitor_url_states_monitor_id"),
        "monitor_url_states",
        ["monitor_id"],
        unique=False,
    )
    op.create_index(
        "uq_monitor_url_states_monitor_url",
        "monitor_url_states",
        ["monitor_id", "url"],
        unique=True,
    )
    op.create_table(
        "product_intelligence_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("source_run_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_run_id"], ["crawl_runs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_intelligence_jobs_source_run_id"),
        "product_intelligence_jobs",
        ["source_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_intelligence_jobs_status"),
        "product_intelligence_jobs",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_intelligence_jobs_user_id"),
        "product_intelligence_jobs",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "review_promotions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("surface", sa.String(length=40), nullable=False),
        sa.Column(
            "approved_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "field_mapping", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["crawl_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_promotions_domain"),
        "review_promotions",
        ["domain"],
        unique=False,
    )
    op.create_index(
        "ix_review_promotions_run_domain",
        "review_promotions",
        ["run_id", "domain"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_promotions_run_id"),
        "review_promotions",
        ["run_id"],
        unique=False,
    )
    op.create_table(
        "enriched_products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("source_run_id", sa.Integer(), nullable=True),
        sa.Column("source_record_id", sa.Integer(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "price_normalized", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("color_family", sa.Text(), nullable=True),
        sa.Column(
            "size_normalized", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("size_system", sa.String(length=32), nullable=True),
        sa.Column("gender_normalized", sa.String(length=32), nullable=True),
        sa.Column(
            "materials_normalized",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("availability_normalized", sa.String(length=32), nullable=True),
        sa.Column(
            "seo_keywords", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("category_path", sa.Text(), nullable=True),
        sa.Column("taxonomy_version", sa.String(length=32), nullable=True),
        sa.Column(
            "intent_attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("audience", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("style_tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "ai_discovery_tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "suggested_bundles", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "diagnostics", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["data_enrichment_jobs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id"], ["crawl_records.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["source_run_id"], ["crawl_runs.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_enriched_products_job_id"),
        "enriched_products",
        ["job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_enriched_products_source_record_id"),
        "enriched_products",
        ["source_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_enriched_products_source_run_id"),
        "enriched_products",
        ["source_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_enriched_products_status"),
        "enriched_products",
        ["status"],
        unique=False,
    )
    op.create_index(
        "uq_enriched_products_source_record",
        "enriched_products",
        ["source_record_id"],
        unique=True,
        postgresql_where=sa.text("source_record_id IS NOT NULL"),
    )
    op.create_table(
        "monitor_snapshot_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("monitor_id", sa.Integer(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("url_identity_key", sa.String(length=255), nullable=False),
        sa.Column(
            "field_values", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["monitor_id"], ["monitor_jobs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["monitor_snapshots.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_monitor_snapshot_records_monitor_id"),
        "monitor_snapshot_records",
        ["monitor_id"],
        unique=False,
    )
    op.create_index(
        "ix_monitor_snapshot_records_monitor_url",
        "monitor_snapshot_records",
        ["monitor_id", "source_url"],
        unique=False,
    )
    op.create_index(
        "ix_monitor_snapshot_records_snapshot",
        "monitor_snapshot_records",
        ["snapshot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monitor_snapshot_records_url_identity_key"),
        "monitor_snapshot_records",
        ["url_identity_key"],
        unique=False,
    )
    op.create_table(
        "monitor_webhook_deliveries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("monitor_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("response_code", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "payload_preview", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"], ["monitor_events.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["monitor_id"], ["monitor_jobs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_monitor_webhook_deliveries_event_id"),
        "monitor_webhook_deliveries",
        ["event_id"],
        unique=False,
    )
    op.create_index(
        "ix_monitor_webhook_deliveries_monitor_created",
        "monitor_webhook_deliveries",
        ["monitor_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monitor_webhook_deliveries_monitor_id"),
        "monitor_webhook_deliveries",
        ["monitor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monitor_webhook_deliveries_status"),
        "monitor_webhook_deliveries",
        ["status"],
        unique=False,
    )
    op.create_table(
        "product_intelligence_source_products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("source_run_id", sa.Integer(), nullable=True),
        sa.Column("source_record_id", sa.Integer(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("brand", sa.String(length=255), nullable=False),
        sa.Column("normalized_brand", sa.String(length=255), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("sku", sa.String(length=255), nullable=False),
        sa.Column("mpn", sa.String(length=255), nullable=False),
        sa.Column("gtin", sa.String(length=255), nullable=False),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(length=16), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=False),
        sa.Column("is_private_label", sa.Boolean(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["product_intelligence_jobs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id"], ["crawl_records.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["source_run_id"], ["crawl_runs.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_intelligence_source_products_brand"),
        "product_intelligence_source_products",
        ["brand"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_intelligence_source_products_job_id"),
        "product_intelligence_source_products",
        ["job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_intelligence_source_products_normalized_brand"),
        "product_intelligence_source_products",
        ["normalized_brand"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_intelligence_source_products_source_record_id"),
        "product_intelligence_source_products",
        ["source_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_intelligence_source_products_source_run_id"),
        "product_intelligence_source_products",
        ["source_run_id"],
        unique=False,
    )
    op.create_table(
        "product_intelligence_candidates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("source_product_id", sa.Integer(), nullable=False),
        sa.Column("candidate_crawl_run_id", sa.Integer(), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("query_used", sa.Text(), nullable=False),
        sa.Column("search_rank", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_crawl_run_id"], ["crawl_runs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["product_intelligence_jobs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_product_id"],
            ["product_intelligence_source_products.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_intelligence_candidates_candidate_crawl_run_id"),
        "product_intelligence_candidates",
        ["candidate_crawl_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_intelligence_candidates_domain"),
        "product_intelligence_candidates",
        ["domain"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_intelligence_candidates_job_id"),
        "product_intelligence_candidates",
        ["job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_intelligence_candidates_source_product_id"),
        "product_intelligence_candidates",
        ["source_product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_intelligence_candidates_status"),
        "product_intelligence_candidates",
        ["status"],
        unique=False,
    )
    op.create_table(
        "product_intelligence_matches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("source_product_id", sa.Integer(), nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column("candidate_record_id", sa.Integer(), nullable=True),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("score_label", sa.String(length=32), nullable=False),
        sa.Column("review_status", sa.String(length=32), nullable=False),
        sa.Column("source_price", sa.Float(), nullable=True),
        sa.Column("candidate_price", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(length=16), nullable=False),
        sa.Column("availability", sa.Text(), nullable=False),
        sa.Column("candidate_url", sa.Text(), nullable=False),
        sa.Column("candidate_domain", sa.String(length=255), nullable=False),
        sa.Column(
            "score_reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "llm_enrichment", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["product_intelligence_candidates.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["candidate_record_id"], ["crawl_records.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["product_intelligence_jobs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_product_id"],
            ["product_intelligence_source_products.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_intelligence_matches_candidate_domain"),
        "product_intelligence_matches",
        ["candidate_domain"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_intelligence_matches_candidate_id"),
        "product_intelligence_matches",
        ["candidate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_intelligence_matches_candidate_record_id"),
        "product_intelligence_matches",
        ["candidate_record_id"],
        unique=False,
    )
    op.create_index(
        "ix_product_intelligence_matches_job_source",
        "product_intelligence_matches",
        ["job_id", "source_product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_intelligence_matches_review_status"),
        "product_intelligence_matches",
        ["review_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_intelligence_matches_score"),
        "product_intelligence_matches",
        ["score"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_intelligence_matches_source_product_id"),
        "product_intelligence_matches",
        ["source_product_id"],
        unique=False,
    )
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_playground_sessions_updated_at()
        RETURNS trigger AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_playground_sessions_updated_at
        BEFORE UPDATE ON playground_sessions
        FOR EACH ROW
        EXECUTE FUNCTION set_playground_sessions_updated_at()
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DROP TRIGGER IF EXISTS trg_playground_sessions_updated_at "
        "ON playground_sessions"
    )
    op.execute("DROP FUNCTION IF EXISTS set_playground_sessions_updated_at()")
    op.drop_index(
        op.f("ix_product_intelligence_matches_source_product_id"),
        table_name="product_intelligence_matches",
    )
    op.drop_index(
        op.f("ix_product_intelligence_matches_score"),
        table_name="product_intelligence_matches",
    )
    op.drop_index(
        op.f("ix_product_intelligence_matches_review_status"),
        table_name="product_intelligence_matches",
    )
    op.drop_index(
        "ix_product_intelligence_matches_job_source",
        table_name="product_intelligence_matches",
    )
    op.drop_index(
        op.f("ix_product_intelligence_matches_candidate_record_id"),
        table_name="product_intelligence_matches",
    )
    op.drop_index(
        op.f("ix_product_intelligence_matches_candidate_id"),
        table_name="product_intelligence_matches",
    )
    op.drop_index(
        op.f("ix_product_intelligence_matches_candidate_domain"),
        table_name="product_intelligence_matches",
    )
    op.drop_table("product_intelligence_matches")
    op.drop_index(
        op.f("ix_product_intelligence_candidates_status"),
        table_name="product_intelligence_candidates",
    )
    op.drop_index(
        op.f("ix_product_intelligence_candidates_source_product_id"),
        table_name="product_intelligence_candidates",
    )
    op.drop_index(
        op.f("ix_product_intelligence_candidates_job_id"),
        table_name="product_intelligence_candidates",
    )
    op.drop_index(
        op.f("ix_product_intelligence_candidates_domain"),
        table_name="product_intelligence_candidates",
    )
    op.drop_index(
        op.f("ix_product_intelligence_candidates_candidate_crawl_run_id"),
        table_name="product_intelligence_candidates",
    )
    op.drop_table("product_intelligence_candidates")
    op.drop_index(
        op.f("ix_product_intelligence_source_products_source_run_id"),
        table_name="product_intelligence_source_products",
    )
    op.drop_index(
        op.f("ix_product_intelligence_source_products_source_record_id"),
        table_name="product_intelligence_source_products",
    )
    op.drop_index(
        op.f("ix_product_intelligence_source_products_normalized_brand"),
        table_name="product_intelligence_source_products",
    )
    op.drop_index(
        op.f("ix_product_intelligence_source_products_job_id"),
        table_name="product_intelligence_source_products",
    )
    op.drop_index(
        op.f("ix_product_intelligence_source_products_brand"),
        table_name="product_intelligence_source_products",
    )
    op.drop_table("product_intelligence_source_products")
    op.drop_index(
        op.f("ix_monitor_webhook_deliveries_status"),
        table_name="monitor_webhook_deliveries",
    )
    op.drop_index(
        op.f("ix_monitor_webhook_deliveries_monitor_id"),
        table_name="monitor_webhook_deliveries",
    )
    op.drop_index(
        "ix_monitor_webhook_deliveries_monitor_created",
        table_name="monitor_webhook_deliveries",
    )
    op.drop_index(
        op.f("ix_monitor_webhook_deliveries_event_id"),
        table_name="monitor_webhook_deliveries",
    )
    op.drop_table("monitor_webhook_deliveries")
    op.drop_index(
        op.f("ix_monitor_snapshot_records_url_identity_key"),
        table_name="monitor_snapshot_records",
    )
    op.drop_index(
        "ix_monitor_snapshot_records_snapshot", table_name="monitor_snapshot_records"
    )
    op.drop_index(
        "ix_monitor_snapshot_records_monitor_url", table_name="monitor_snapshot_records"
    )
    op.drop_index(
        op.f("ix_monitor_snapshot_records_monitor_id"),
        table_name="monitor_snapshot_records",
    )
    op.drop_table("monitor_snapshot_records")
    op.drop_index(
        "uq_enriched_products_source_record",
        table_name="enriched_products",
        postgresql_where=sa.text("source_record_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_enriched_products_status"), table_name="enriched_products")
    op.drop_index(
        op.f("ix_enriched_products_source_run_id"), table_name="enriched_products"
    )
    op.drop_index(
        op.f("ix_enriched_products_source_record_id"), table_name="enriched_products"
    )
    op.drop_index(op.f("ix_enriched_products_job_id"), table_name="enriched_products")
    op.drop_table("enriched_products")
    op.drop_index(op.f("ix_review_promotions_run_id"), table_name="review_promotions")
    op.drop_index("ix_review_promotions_run_domain", table_name="review_promotions")
    op.drop_index(op.f("ix_review_promotions_domain"), table_name="review_promotions")
    op.drop_table("review_promotions")
    op.drop_index(
        op.f("ix_product_intelligence_jobs_user_id"),
        table_name="product_intelligence_jobs",
    )
    op.drop_index(
        op.f("ix_product_intelligence_jobs_status"),
        table_name="product_intelligence_jobs",
    )
    op.drop_index(
        op.f("ix_product_intelligence_jobs_source_run_id"),
        table_name="product_intelligence_jobs",
    )
    op.drop_table("product_intelligence_jobs")
    op.drop_index("uq_monitor_url_states_monitor_url", table_name="monitor_url_states")
    op.drop_index(
        op.f("ix_monitor_url_states_monitor_id"), table_name="monitor_url_states"
    )
    op.drop_table("monitor_url_states")
    op.drop_index(op.f("ix_monitor_snapshots_run_id"), table_name="monitor_snapshots")
    op.drop_index(
        op.f("ix_monitor_snapshots_monitor_id"), table_name="monitor_snapshots"
    )
    op.drop_index(
        "ix_monitor_snapshots_monitor_created", table_name="monitor_snapshots"
    )
    op.drop_table("monitor_snapshots")
    op.drop_index(op.f("ix_monitor_events_run_id"), table_name="monitor_events")
    op.drop_index(
        op.f("ix_monitor_events_notification_status"), table_name="monitor_events"
    )
    op.drop_index(op.f("ix_monitor_events_monitor_id"), table_name="monitor_events")
    op.drop_index("ix_monitor_events_monitor_detected", table_name="monitor_events")
    op.drop_index(op.f("ix_monitor_events_field_name"), table_name="monitor_events")
    op.drop_index(op.f("ix_monitor_events_event_type"), table_name="monitor_events")
    op.drop_index(op.f("ix_monitor_events_detected_at"), table_name="monitor_events")
    op.drop_index(op.f("ix_monitor_events_condition_met"), table_name="monitor_events")
    op.drop_table("monitor_events")
    op.drop_index(op.f("ix_llm_cost_log_run_id"), table_name="llm_cost_log")
    op.drop_table("llm_cost_log")
    op.drop_index(
        "ix_in_app_notifications_user_read_created", table_name="in_app_notifications"
    )
    op.drop_index(
        op.f("ix_in_app_notifications_user_id"), table_name="in_app_notifications"
    )
    op.drop_index(
        op.f("ix_in_app_notifications_read"), table_name="in_app_notifications"
    )
    op.drop_index(
        op.f("ix_in_app_notifications_monitor_id"), table_name="in_app_notifications"
    )
    op.drop_table("in_app_notifications")
    op.drop_index(
        op.f("ix_domain_field_feedback_surface"), table_name="domain_field_feedback"
    )
    op.drop_index(
        op.f("ix_domain_field_feedback_source_run_id"),
        table_name="domain_field_feedback",
    )
    op.drop_index(
        op.f("ix_domain_field_feedback_field_name"), table_name="domain_field_feedback"
    )
    op.drop_index(
        "ix_domain_field_feedback_domain_surface", table_name="domain_field_feedback"
    )
    op.drop_table("domain_field_feedback")
    op.drop_index(
        op.f("ix_data_enrichment_jobs_user_id"), table_name="data_enrichment_jobs"
    )
    op.drop_index(
        op.f("ix_data_enrichment_jobs_status"), table_name="data_enrichment_jobs"
    )
    op.drop_index(
        op.f("ix_data_enrichment_jobs_source_run_id"), table_name="data_enrichment_jobs"
    )
    op.drop_table("data_enrichment_jobs")
    op.drop_index(
        "uq_crawl_records_run_identity",
        table_name="crawl_records",
        postgresql_where=sa.text("url_identity_key IS NOT NULL"),
    )
    op.drop_index(op.f("ix_crawl_records_run_id"), table_name="crawl_records")
    op.drop_index("ix_crawl_records_run_content_fp", table_name="crawl_records")
    op.drop_index(
        op.f("ix_crawl_records_enrichment_status"), table_name="crawl_records"
    )
    op.drop_table("crawl_records")
    op.drop_index(op.f("ix_crawl_logs_run_id"), table_name="crawl_logs")
    op.drop_table("crawl_logs")
    op.drop_index(
        op.f("ix_playground_sessions_user_id"), table_name="playground_sessions"
    )
    op.drop_table("playground_sessions")
    op.drop_index(op.f("ix_monitor_jobs_user_id"), table_name="monitor_jobs")
    op.drop_index("ix_monitor_jobs_status_priority_next_run", table_name="monitor_jobs")
    op.drop_index(op.f("ix_monitor_jobs_status"), table_name="monitor_jobs")
    op.drop_index(op.f("ix_monitor_jobs_priority"), table_name="monitor_jobs")
    op.drop_table("monitor_jobs")
    op.drop_index(op.f("ix_crawl_runs_user_id"), table_name="crawl_runs")
    op.drop_index(op.f("ix_crawl_runs_status"), table_name="crawl_runs")
    op.drop_table("crawl_runs")
    op.drop_index(op.f("ix_api_keys_user_id"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_key_prefix"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_key_hash"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_is_active"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("llm_configs")
    op.drop_index("uq_host_protection_memory_host", table_name="host_protection_memory")
    op.drop_table("host_protection_memory")
    op.drop_index(
        "uq_domain_run_profiles_domain_surface", table_name="domain_run_profiles"
    )
    op.drop_table("domain_run_profiles")
    op.drop_index(op.f("ix_domain_memory_surface"), table_name="domain_memory")
    op.drop_index(op.f("ix_domain_memory_domain"), table_name="domain_memory")
    op.drop_table("domain_memory")
    op.drop_index("uq_domain_cookie_memory_domain", table_name="domain_cookie_memory")
    op.drop_table("domain_cookie_memory")
    # ### end Alembic commands ###
